"""The ``induction.md`` report: the per-interval boosting trace, in the house report style.

For each induced interval it writes the iteration table (each accepted rule, its ΔL split into
fit and rule-cost bits, the exact-match and word-count movement, and its placement), the shrink
log, and the headline before→after. It follows the conventions of ``whatif.md`` and
``diagnosis.md`` — a stderr summary line plus a Markdown file written to the project directory.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

from src.fortis.induction.boost import InducedInterval
from src.fortis.models.rules import RuleInventory

if TYPE_CHECKING:
    from src.fortis.induction.refine import RefineTrace


def _toml_string(value: str) -> str:
    """Escape a string for a TOML basic (double-quoted) value."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render_induced_rules(inventory: RuleInventory) -> str:
    """Serialize a composed rule inventory to a loadable ``rules.toml`` (plan §3.3, §4.4).

    Writes one ``[id]`` table per rule in ``(time, file-order)``, each carrying ``time``,
    ``name``, ``definition`` (the notation the loader re-parses), and ``description``. Written by
    hand because the project ships no TOML-writer dependency; the round trip ``induce → load →
    grade`` is itself a test. Application mode is the default (``simultaneous``) for every
    induced rule, so it is omitted.
    """
    lines = [
        "# Induced sound-change cascade — generated by the rule inducer.",
        "# Loadable as a normal rules.toml; times are real (composed from the interval spans).",
        "",
    ]
    for time in sorted(inventory.keys(), key=lambda t: (t is None, t)):
        for rule in inventory[time]:
            lines.append(f"[{rule.id}]")
            if rule.time is not None:
                lines.append(f"time = {rule.time}")
            if rule.name is not None:
                lines.append(f"name = {_toml_string(rule.name)}")
            lines.append(f"definition = {_toml_string(rule.raw_definition)}")
            if rule.description is not None:
                lines.append(f"description = {_toml_string(rule.description)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _placement_label(placement: int, rules_before: int) -> str:
    """How a rule was placed: ``append`` (the boosting default) or an explicit earlier index.

    A step is an append when it went to the end of the cascade as it stood *then* — i.e. its
    index equalled the number of rules already accepted (*rules_before*). A smaller index is a
    genuine placement-search insertion that fed a later rule.
    """
    if placement < 0 or placement >= rules_before:
        return "append"
    return f"@{placement}"


def render_induction(
    intervals: list[InducedInterval], where: str, trace: RefineTrace | None = None
) -> str:
    """The full ``induction.md`` report: the per-interval traces, then the Phase-B refinement."""
    lines = [
        f"# Induction — {where}",
        "",
        "Each interval's rule cascade, induced by greedy MDL boosting from the attested source",
        "forms toward the attested targets. A rule is accepted only when it strictly lowers the",
        "description length `L = fit_bits + rule_bits` — the bits it saves in the residual must",
        "exceed the bits it costs to write. `ΔL` is that change (negative = a net saving), split",
        "into its fit and rule-cost parts. `place` is where the rule was inserted in the",
        "cascade (`append`, or `@i` when the placement search found an earlier slot fed a later",
        "rule).",
        "",
    ]
    for interval in intervals:
        lines += _interval_section(interval)
    if trace is not None:
        lines += _refine_section(trace)
    return "\n".join(lines).rstrip() + "\n"


def _refine_section(trace: RefineTrace) -> list[str]:
    """The Phase-B composition/refinement summary: what global shrink and boosting changed."""
    lines = ["## Phase B — global refinement", ""]
    if trace.start_score is not None and trace.final_score is not None:
        lines += [
            f"Composed cascade run from the true inputs over the whole lexicon: "
            f"L **{trace.start_score.total:.0f} → {trace.final_score.total:.0f}**, "
            f"final exact **{trace.start_score.exact} → {trace.final_score.exact} / "
            f"{trace.final_score.graded}**.",
            "",
        ]
    if trace.removed:
        lines += [f"**Global shrink** retired {len(trace.removed)} rule(s):", ""]
        lines += [f"- {entry}" for entry in trace.removed]
        lines.append("")
    if trace.added:
        lines += [f"**Final-residual boosting** appended {len(trace.added)} rule(s):", ""]
        lines += [f"- `{definition}`" for definition in trace.added]
        lines.append("")
    if not trace.removed and not trace.added:
        lines += ["Nothing changed — the composed cascade was already at a fixpoint.", ""]
    return lines


def _interval_section(interval: InducedInterval) -> list[str]:
    exact_pct = interval.final_exact / interval.graded if interval.graded else 0.0
    lines = [
        f"## Interval `{interval.label}`",
        "",
        f"**{interval.start_exact} → {interval.final_exact} / {interval.graded} exact** "
        f"({exact_pct:.0%}), fit **{interval.start_fit:.0f} → {interval.final_fit:.0f}** bits, "
        f"**{len(interval.rules)} rules** induced — stopped: _{interval.stopped}_.",
        "",
    ]
    if not interval.steps:
        lines += ["No rule lowered the loss — nothing induced.", ""]
        return lines
    lines += [
        "| # | rule | ΔL | Δfit | cost | words | exact | place |",
        "| ---: | --- | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for number, step in enumerate(interval.steps, start=1):
        lines.append(
            f"| {number} | `{step.definition}` | {step.delta_l:.0f} | {step.delta_fit:.0f} "
            f"| {step.rule_cost:.0f} | {step.moved} | {step.exact_before}→{step.exact_after} "
            f"| {_placement_label(step.placement, number - 1)} |"
        )
    lines.append("")
    if interval.shrink_log:
        lines += [
            f"**Shrink pass** removed {len(interval.shrink_log)} now-redundant rule(s):",
            "",
        ]
        lines += [f"- {entry}" for entry in interval.shrink_log]
        lines.append("")
    return lines


def induction_summary_line(intervals: list[InducedInterval]) -> str:
    """A one-line headline for stderr, aggregating the induced intervals."""
    rules = sum(len(interval.rules) for interval in intervals)
    exact = sum(interval.final_exact for interval in intervals)
    start = sum(interval.start_exact for interval in intervals)
    graded = sum(interval.graded for interval in intervals)
    return (
        f"induced {rules} rule(s) across {len(intervals)} interval(s); "
        f"exact {start} → {exact} / {graded} — see induction.md"
    )
