# Segmental
"ʰ" = { tier = "segment", type = "after", bundle = "-vc, 1 glap, 0 tns" }
"ʱ" = { tier = "segment", type = "after", bundle = "+vc, 1 glap, -1 tns" }
"ʷ" = { tier = "segment", type = "after", bundle = "+labial, +rounded" }
"ⁿ" = { tier = "segment", type = "before", bundle = "nasal" }
"̩" = { tier = "segment", type = "combining", bundle = "+syll" }
"̯" = { tier = "segment", type = "combining", bundle = "-syll" }
# Length
"ː" = { tier = "segment", type = "after", bundle = "length: long"}
"ːː" = { tier = "segment", type = "after", bundle = "length: overlong"}
# Primary stress
"ˈ" = { tier = "syllable", type = "before", bundle = "stress: primary", default = true }
# Tone diacritics
"̋" = { tier = "syllable", type = "combining", bundle = "tone: 5" }
"́" = { tier = "syllable", type = "combining", bundle = "tone: 4" }
"̄" = { tier = "syllable", type = "combining", bundle = "tone: 3" }
"̀" = { tier = "syllable", type = "combining", bundle = "tone: 2" }
"̏" = { tier = "syllable", type = "combining", bundle = "tone: 1" }
"̂" = { tier = "syllable", type = "combining", bundle = "tone: 5>3" }
"̌" = { tier = "syllable", type = "combining", bundle = "tone: 3>5" }
"᷇" = { tier = "syllable", type = "combining", bundle = "tone: 5>3" }
"᷆" = { tier = "syllable", type = "combining", bundle = "tone: 3>1" }
"᷄" = { tier = "syllable", type = "combining", bundle = "tone: 3>5" }
"᷅" = { tier = "syllable", type = "combining", bundle = "tone: 1>3" }
"᷈" = { tier = "syllable", type = "combining", bundle = "tone: 5>3>5" }
"᷉" = { tier = "syllable", type = "combining", bundle = "tone: 3>1>3" }
# Tone letters
"˥" = { tier = "syllable", type = "after", bundle = "tone: 5", default = true, contour = true}
"˦" = { tier = "syllable", type = "after", bundle = "tone: 4", default = true, contour = true}
"˧" = { tier = "syllable", type = "after", bundle = "tone: 3", default = true, contour = true}
"˨" = { tier = "syllable", type = "after", bundle = "tone: 2", default = true, contour = true}
"˩" = { tier = "syllable", type = "after", bundle = "tone: 1", default = true, contour = true}
