# Segmental
"ʰ" = { tier = "segment", kind = "after", bundle = "1 glap" }
"ʱ" = { tier = "segment", kind = "after", bundle = "+vc, 1 glap, -1 tns" }
"ʷ" = { tier = "segment", kind = "after", bundle = "+labial, +rounded" }
"ʲ" = { tier = "segment", kind = "after", bundle = "+front, +high" }
"ⁿ" = { tier = "segment", kind = "before", bundle = "nasal: 1>none" }
"̃" = { tier = "segment", kind = "combining", bundle = "nasal: 1" }
"̩" = { tier = "segment", kind = "combining", bundle = "+syll" }
"̯" = { tier = "segment", kind = "combining", bundle = "-syll" }
"ː" = { tier = "segment", kind = "after", bundle = "length: long"}
"ːː" = { tier = "segment", kind = "after", bundle = "length: overlong"}
# Syllable
## Primary stress
"ˈ" = { tier = "syllable", kind = "before", bundle = "stress: primary", default = true, marks_boundary = true}
## Tone diacritics
"̋" = { tier = "syllable", kind = "combining", bundle = "tone: 5" }
"́" = { tier = "syllable", kind = "combining", bundle = "tone: 4" }
"̄" = { tier = "syllable", kind = "combining", bundle = "tone: 3" }
"̀" = { tier = "syllable", kind = "combining", bundle = "tone: 2" }
"̏" = { tier = "syllable", kind = "combining", bundle = "tone: 1" }
"̂" = { tier = "syllable", kind = "combining", bundle = "tone: 5>3" }
"̌" = { tier = "syllable", kind = "combining", bundle = "tone: 3>5" }
"᷇" = { tier = "syllable", kind = "combining", bundle = "tone: 5>3" }
"᷆" = { tier = "syllable", kind = "combining", bundle = "tone: 3>1" }
"᷄" = { tier = "syllable", kind = "combining", bundle = "tone: 3>5" }
"᷅" = { tier = "syllable", kind = "combining", bundle = "tone: 1>3" }
"᷈" = { tier = "syllable", kind = "combining", bundle = "tone: 5>3>5" }
"᷉" = { tier = "syllable", kind = "combining", bundle = "tone: 3>1>3" }
## Tone letters
"˥" = { tier = "syllable", kind = "after", bundle = "tone: 5", default = true, contour = true}
"˦" = { tier = "syllable", kind = "after", bundle = "tone: 4", default = true, contour = true}
"˧" = { tier = "syllable", kind = "after", bundle = "tone: 3", default = true, contour = true}
"˨" = { tier = "syllable", kind = "after", bundle = "tone: 2", default = true, contour = true}
"˩" = { tier = "syllable", kind = "after", bundle = "tone: 1", default = true, contour = true}
