[laryngeal_coloring]
time = -2000
name = "Laryngeal coloring"
description = "Allophonic colouring of /e/ adjacent to laryngeal consonants"
definition = "xe → xa"

[centumization]
time = -2000
name = "Centumization"
description = "Merging of PIE 'palatovelar' and 'velar' plosives"
definition = "[+cons, -sonorant, +back, +front] → [front: none]"

[u_epenthesis]
time = -2000
name = "'u' epenthesis"
description = "Epenthesis of /u/ before the syllabic sonorants"
definition = "∅ [+cons, +syll] → u [-syll]"

[backness_harmony]
time = 1300
name = "Backness harmony"
description = "Backness spreads rightward from a vowel onto following vowels."
definition = "[+syll] → [α fr, β bk] / [+syll, α fr, β bk] [-syll]* _"
application = "left_to_right"
