# Words for testing phonological derivation.
# Format: IPA = "gloss"

"ˈħenti" = "in front"
"meħˈteːr" = "mother"
"ˈʁʷeroː" = "eagle"
"ˈbʱleʁʷmoː" = "flower"
"kʲm̩ˈtom" = "hundred"
"ˈwergʲom" = "work"
"ˈgʲʱχjeti" = "to go"
"n̩ˈter" = "inside"
"ˈwl̩kʷos" = "wolf"
"ˈħr̩tkʲos" = "bear"
"ˈwr̩mis" = "worm"
"widˈstos" = "known"
"ˈkajdstis" = "a calling"
"ˈseχmoː" = "seeds"
"ˈχdontm̩" = "tooth"
"ˈχesti" = "is"
"eħes" = "eh₂-stem nom. pl."
"dkʲm̩ˈtoχom" = "of the tens"
"gʷiˈʁʷwos" = "alive"
"ˈpħteːr" = "father"
"ˈsamħdʱos" = "sand"
"ˈekʲwos" = "horse"
"ˈnokʷts" = "night"
"ˈgʷm̩tis" = "walking"
"ˈgʷʰn̩tis" = "killing"
"ˈwojde" = "he/she/it knows"
"ˈtosjo" = "of that"
"n̩ˈswe" = "us"
"ˈtod" = "that"
"ˈkatus" = "fight"
"ˈħekʲsleħ" = "axle"
"ˈkʷod" = "who"
"ˈkħptos" = "grabbed"
"okʲˈtoːw" = "eight"
"ˈnokʷtm̩" = "night, acc."
"ˈħeboːl" = "apple"
"ˈgʷemeti" = "(s)he will step, subj."
"ˈbʰereti" = "(s)he is carrying"
"ˈdʰoχmos" = "thing put"
"ˈgʰans" = "goose"
"ˈsongʷʰos" = "song"
"uˈperi" = "over"
"tewˈteħ" = "tribe"
"ħjuħn̩ˈkʲos" = "young"
"kʷeˈkʷleħ" = "wheels"
"ˈχregʷeses" = "of darkness"
"χesmi" = "I am" # generally unaccented
"χsenti" = "they are" # generally unaccented
"ˈgʷʰedʰjeti" = "(s)he is asking for"
"ˈbʰerowos" = "they two carry"
"ˈlegʰjeti" = "(s)he is lying down"
"ˈlegʰjonti" = "they are lying down"
"ˈtrejes" = "three"
"ˈgʰostejes" = "strangers"
"ˈsweħdus" = "sweet"
"ˈtom" = "that, acc. masc."
"ˈdekʲm̩d" = "ten"
"ˈdʰedʰeχm" = "I was putting"
"takˈχjonti" = "they are silent"
"takˈχjeti" = "(s)he is silent"
"tn̩ˈħus" = "thin, msc."
"tn̩ˈħwiħ" = "thin, fem."
"pl̩χˈnos" = "full"
"ˈsnojgʷʰos" = "snow"
"ˈmedʰjos" = "middle"
"ˈnewjos" = "new"
"dejˈwos" = "god"
"ˈen" = "in"
"ˈsengʷʰeti" =  "(s)he chants"
"ˈħejeri" = "in the morning"
"ˈstħjonti" = "they stand"
"ˈkʲonketi" = "(s)he hangs"
