# Words for testing phonological derivation.
# Format: IPA = "gloss"

"ˈħenti" = "in front"
"meħˈteːr" = "mother"
"ˈʁʷeroː" = "eagle"
"ˈbʱleʁʷmoː" = "flower"
"kʲm̩ˈtom" = "hundred"
"ˈwergʲom" = "work"
"ˈgʲʱχjeti" = "to go"
"n̩ˈter" = "inside"
"ˈwl̩kʷos" = "wolf"
"ˈħr̩tkʲos" = "bear"
"ˈwr̩mis" = "worm"
"widˈstos" = "known"
"ˈkajdstis" = "a calling"
"ketus" = "fight"
"ˈseχmoː" = "seeds"
"ˈχdontm̩" = "tooth"
"ˈχesti" = "is"
"gʷiˈʁʷwos" = "alive"
"ˈpħteːr" = "father"
"ˈsamħdʱos" = "sand"
"ˈekʲwos" = "horse"
"ˈnokʷts" = "night"
"ˈgʷemtis" = "walking"
"dkʲm̩ˈtoχom" = "of the tens"
